
package com.rust.ws.service.submit;

import javax.xml.namespace.*;
import javax.xml.ws.*;

import java.net.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubmitServiceImplService", targetNamespace = "http://submit.service.ws.rust.com/", wsdlLocation = "http://10.28.11.159:9000/services/submitService?wsdl")
public class SubmitServiceImplService
    extends Service
{

    private final static URL SUBMITSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBMITSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SUBMITSERVICEIMPLSERVICE_QNAME = new QName("http://submit.service.ws.rust.com/", "SubmitServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.28.11.159:9000/services/submitService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBMITSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SUBMITSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SubmitServiceImplService() {
        super(__getWsdlLocation(), SUBMITSERVICEIMPLSERVICE_QNAME);
    }

    public SubmitServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBMITSERVICEIMPLSERVICE_QNAME, features);
    }

    public SubmitServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SUBMITSERVICEIMPLSERVICE_QNAME);
    }

    public SubmitServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBMITSERVICEIMPLSERVICE_QNAME, features);
    }

    public SubmitServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubmitServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubmitServiceImpl
     */
    @WebEndpoint(name = "SubmitServiceImplPort")
    public SubmitServiceImpl getSubmitServiceImplPort() {
        return super.getPort(new QName("http://submit.service.ws.rust.com/", "SubmitServiceImplPort"), SubmitServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubmitServiceImpl
     */
    @WebEndpoint(name = "SubmitServiceImplPort")
    public SubmitServiceImpl getSubmitServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://submit.service.ws.rust.com/", "SubmitServiceImplPort"), SubmitServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBMITSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SUBMITSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SUBMITSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
