
package com.rust.ws.service.submit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubmitServiceImpl", targetNamespace = "http://submit.service.ws.rust.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubmitServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.rust.ws.service.submit.RetBean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "http://submit.service.ws.rust.com/", className = "com.rust.ws.service.submit.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://submit.service.ws.rust.com/", className = "com.rust.ws.service.submit.SubmitResponse")
    @Action(input = "http://submit.service.ws.rust.com/SubmitServiceImpl/submitRequest", output = "http://submit.service.ws.rust.com/SubmitServiceImpl/submitResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://submit.service.ws.rust.com/SubmitServiceImpl/submit/Fault/Exception")
    })
    public RetBean submit(
			@WebParam(name = "arg0", targetNamespace = "")
					ReqBean arg0)
        throws Exception_Exception
    ;

}
